### ISSUE TITLE
jschunk58 GitHub Workflow

### ISSUE THREAD

**Issue by jschunk58** [githubteacher/intro-to-github-may-2016#61]
## Workflow Steps

[] Create a new Branch
[] Add Commits
[] Open a Pull Request
[] Discuss and Review your code/documentation
[] Merge

**Comment by jschunk58** [comment]
- [x] Create a new Branch
- [x]  Add Commits
- [x] Open a Pull Request
- [x] Discuss and Review your code/documentation
- [x] Merge

**Comment by jschunk58** [comment]
Ready to ship

**Comment by ThiagoMSArrais** [comment]
Good afternoon,

please take off my email this notification, because my inbox is full about
emails issues channel githubteacher.

thank's

Thiago Arrais

2016-05-09 13:55 GMT-03:00 Joe Schunk notifications@github.com:
